version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
artifacts:
- path: XInput Hotkeys\bin\Release
  name: XInput Hotkeys
deploy:
- provider: Environment
  name: Github
  on:
    branch: master